"""Add asteroid catalog table

Revision ID: 4e15e74c0778
Revises: 0f7dcc26ea5b
Create Date: 2025-11-20 11:11:17.232062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e15e74c0778'
down_revision: Union[str, Sequence[str], None] = '0f7dcc26ea5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asteroid_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('designation', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('discovery_date', sa.Date(), nullable=True),
    sa.Column('epoch_jd', sa.Float(), nullable=False),
    sa.Column('perihelion_distance_au', sa.Float(), nullable=False),
    sa.Column('eccentricity', sa.Float(), nullable=False),
    sa.Column('inclination_deg', sa.Float(), nullable=False),
    sa.Column('arg_perihelion_deg', sa.Float(), nullable=False),
    sa.Column('ascending_node_deg', sa.Float(), nullable=False),
    sa.Column('mean_anomaly_deg', sa.Float(), nullable=False),
    sa.Column('semi_major_axis_au', sa.Float(), nullable=False),
    sa.Column('absolute_magnitude', sa.Float(), nullable=True),
    sa.Column('slope_parameter', sa.Float(), nullable=True),
    sa.Column('current_magnitude', sa.Float(), nullable=True),
    sa.Column('diameter_km', sa.Float(), nullable=True),
    sa.Column('albedo', sa.Float(), nullable=True),
    sa.Column('spectral_type', sa.String(length=10), nullable=True),
    sa.Column('rotation_period_hours', sa.Float(), nullable=True),
    sa.Column('asteroid_type', sa.String(length=20), nullable=True),
    sa.Column('data_source', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('designation')
    )
    op.create_index(op.f('ix_asteroid_catalog_id'), 'asteroid_catalog', ['id'], unique=False)
    op.drop_index('ix_dso_catalog_caldwell_number', table_name='dso_catalog')
    op.create_index(op.f('ix_telescope_execution_targets_execution_id'), 'telescope_execution_targets', ['execution_id'], unique=False)
    op.create_foreign_key(None, 'telescope_execution_targets', 'telescope_executions', ['execution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telescope_execution_targets', type_='foreignkey')
    op.drop_index(op.f('ix_telescope_execution_targets_execution_id'), table_name='telescope_execution_targets')
    op.create_index('ix_dso_catalog_caldwell_number', 'dso_catalog', ['caldwell_number'], unique=False)
    op.drop_index(op.f('ix_asteroid_catalog_id'), table_name='asteroid_catalog')
    op.drop_table('asteroid_catalog')
    # ### end Alembic commands ###
