"""add saved_plan_id to telescope_executions

Revision ID: 7c043c79d64c
Revises: 1ba996993cf6
Create Date: 2025-11-16 16:53:05.830942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c043c79d64c'
down_revision: Union[str, Sequence[str], None] = '1ba996993cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telescope_executions', sa.Column('saved_plan_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'telescope_executions', 'saved_plans', ['saved_plan_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telescope_executions', type_='foreignkey')
    op.drop_column('telescope_executions', 'saved_plan_id')
    # ### end Alembic commands ###
