"""Add telescope execution tracking tables

Revision ID: 8138601c67ee
Revises: f067834e5435
Create Date: 2025-11-16 15:58:20.723191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8138601c67ee'
down_revision: Union[str, Sequence[str], None] = 'f067834e5435'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telescope_execution_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('target_index', sa.Integer(), nullable=False),
    sa.Column('target_name', sa.String(length=100), nullable=False),
    sa.Column('catalog_id', sa.String(length=50), nullable=True),
    sa.Column('ra_hours', sa.Float(), nullable=False),
    sa.Column('dec_degrees', sa.Float(), nullable=False),
    sa.Column('object_type', sa.String(length=50), nullable=True),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('scheduled_start_time', sa.DateTime(), nullable=False),
    sa.Column('scheduled_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('recommended_frames', sa.Integer(), nullable=True),
    sa.Column('recommended_exposure_seconds', sa.Integer(), nullable=True),
    sa.Column('started', sa.Boolean(), nullable=True),
    sa.Column('goto_completed', sa.Boolean(), nullable=True),
    sa.Column('focus_completed', sa.Boolean(), nullable=True),
    sa.Column('imaging_started', sa.Boolean(), nullable=True),
    sa.Column('imaging_completed', sa.Boolean(), nullable=True),
    sa.Column('actual_exposures', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telescope_execution_targets_id'), 'telescope_execution_targets', ['id'], unique=False)
    op.create_table('telescope_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.String(length=50), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('total_targets', sa.Integer(), nullable=False),
    sa.Column('current_target_index', sa.Integer(), nullable=True),
    sa.Column('current_target_name', sa.String(length=100), nullable=True),
    sa.Column('current_phase', sa.String(length=50), nullable=True),
    sa.Column('targets_completed', sa.Integer(), nullable=True),
    sa.Column('targets_failed', sa.Integer(), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('elapsed_seconds', sa.Integer(), nullable=True),
    sa.Column('estimated_remaining_seconds', sa.Integer(), nullable=True),
    sa.Column('park_when_done', sa.Boolean(), nullable=True),
    sa.Column('telescope_host', sa.String(length=100), nullable=True),
    sa.Column('telescope_port', sa.Integer(), nullable=True),
    sa.Column('execution_result', sa.JSON(), nullable=True),
    sa.Column('error_log', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telescope_executions_celery_task_id'), 'telescope_executions', ['celery_task_id'], unique=True)
    op.create_index(op.f('ix_telescope_executions_execution_id'), 'telescope_executions', ['execution_id'], unique=True)
    op.create_index(op.f('ix_telescope_executions_id'), 'telescope_executions', ['id'], unique=False)
    op.create_index(op.f('ix_telescope_executions_state'), 'telescope_executions', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telescope_executions_state'), table_name='telescope_executions')
    op.drop_index(op.f('ix_telescope_executions_id'), table_name='telescope_executions')
    op.drop_index(op.f('ix_telescope_executions_execution_id'), table_name='telescope_executions')
    op.drop_index(op.f('ix_telescope_executions_celery_task_id'), table_name='telescope_executions')
    op.drop_table('telescope_executions')
    op.drop_index(op.f('ix_telescope_execution_targets_id'), table_name='telescope_execution_targets')
    op.drop_table('telescope_execution_targets')
    # ### end Alembic commands ###
